// Generate packages/qr/src/css/qr.css from the QR_CSS constant in src/styles.ts.
//
// The stylesheet has two consumers — the runtime <style> injection and the
// `@liquidglassjs/qr/css` entry — and they must be byte-identical, so the TS
// constant is the single source and this writes the shipped .css file. Wired
// into the qr package's `prepack` (alongside sync-license.mjs) so a published
// tarball can never carry a stale stylesheet. Also runnable directly.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(repoRoot, 'packages/qr/src/styles.ts');
const dest = join(repoRoot, 'packages/qr/src/css/qr.css');

const ts = readFileSync(src, 'utf8');
const match = ts.match(/export const QR_CSS = `([\s\S]*?)`;/);
if (!match) {
  console.error(`[sync-qr-css] could not find the QR_CSS template literal in ${src}`);
  process.exit(1);
}

const banner = `/* GENERATED by scripts/sync-qr-css.mjs from packages/qr/src/styles.ts — do not edit. */\n`;
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, `${banner}${match[1]}\n`);
console.log(`[sync-qr-css] QR_CSS -> ${dest}`);
